#!/usr/bin/env python3
# -*- coding: utf-8 -*-

AWS_POOL_MAX_AGE = -4  # in days default -4

AWS_LEAST_RANGE_INFO = {0: "AMAZON", 1: "EC2"}
# Full list of services in ip-ranges
# AMAZON
# AMAZON_CONNECT
# API_GATEWAY
# CLOUD9
# CLOUDFRONT
# CODEBUILD
# DYNAMODB
# EC2
# EC2_INSTANCE_CONNECT
# GLOBALACCELERATOR
# ROUTE53
# ROUTE53_HEALTHCHECKS
# S3
# WORKSPACES_GATEWAYS
